package com.dgranda.nominaec.calculation;

/**
 * Identifiers of the legal parameters stored in {@code legal_parameters}.
 * Only the keys live in code; every value is loaded from the database by validity date.
 */
public enum ParameterCode {
    SBU,
    IESS_PERSONAL_RATE,
    IESS_EMPLOYER_RATE,
    IECE_RATE,
    SECAP_RATE,
    RESERVE_FUND_RATE,
    OVERTIME_SUPPLEMENTARY_SURCHARGE,
    OVERTIME_EXTRAORDINARY_SURCHARGE,
    OVERTIME_SUPPLEMENTARY_MAX_MONTH,
    MONTHLY_HOURS_BASE,
    FULL_TIME_WEEKLY_HOURS,
    THIRTEENTH_DIVISOR,
    FOURTEENTH_DIVISOR,
    VACATION_PROVISION_DIVISOR,
    VACATION_BASE_DAYS,
    VACATION_EXTRA_AFTER_YEARS,
    VACATION_EXTRA_MAX_DAYS,
    BASIC_FAMILY_BASKET,
    PERSONAL_EXPENSE_REBATE_RATE,
    PERSONAL_EXPENSE_CATASTROPHIC_BASKETS,
    SEVERANCE_BONUS_RATE,
    SEVERANCE_PRORATE_FRACTION,
    DISMISSAL_MIN_MONTHS,
    DISMISSAL_THRESHOLD_YEARS,
    DISMISSAL_MAX_MONTHS,
    PROFIT_SHARING_WORKERS,
    PROFIT_SHARING_DEPENDENTS
}
